version: '3.8'

services:
  app:
    build: .
    ports:
      - "8000:8000"
    depends_on:
      redis:
        condition: service_started

  redis:
    image: redis:7.0.9-alpine3.17
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

  test:
    build:
      context: .
      dockerfile: Dockerfile.test
    depends_on:
      - app
      - redis

volumes:
  redis-data: