FROM golang:1.17-alpine3.14 AS builder

WORKDIR /app

COPY . .

RUN go mod download && \
    export GOPROXY=direct && \
    CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o app .

FROM golang:1.17-alpine3.14 AS test

WORKDIR /app

COPY . .

RUN apk add --no-cache build-base

CMD ["go", "test", "-v", "./...", "-coverprofile", "cover.out"]
